---

- name: postfixを全部飛指定のアドレスへ飛ばす
  template: src=main.cf.j2 dest=/etc/postfix/main.cf owner=root group=root mode=0644
  notify: restart postfix
- template: src=aliases.reg.j2 dest=/etc/postfix/aliases.reg owner=root group=root mode=0644
  notify: restart postfix

